-- Sabendo-se que a tabela 

SELECT DISTINCT(ID_COLABORADOR) AS "REGISTRO" 
FROM dependente;

SELECT DISTINCT(ID_COLABORADOR) ALIAS "REGISTRO"
 FROM dependente;

 SELECT VARIANCE(ID_COLABORADOR) AS "REGISTRO" 
 FROM dependente;

 SELECT DISTINCT(ID_COLABORADOR) AS "REGISTRO" 
 FROM dependente
 WHERE id_colaborador < 3548;

 